version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  quizapplication:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app
volumes:
  postgres_data:  
